# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aiServer.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x61iServer.proto\x12\x0eModelServer.v1\"0\n\x0eRequestExample\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"\x16\n\x07pingMsg\x12\x0b\n\x03msg\x18\x01 \x01(\t\"#\n\x06status\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0b\n\x03msg\x18\x02 \x01(\t2\x93\x01\n\rAIModelServer\x12I\n\x0fprocessInstance\x12\x1e.ModelServer.v1.RequestExample\x1a\x16.ModelServer.v1.status\x12\x37\n\x04ping\x12\x17.ModelServer.v1.pingMsg\x1a\x16.ModelServer.v1.statusb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aiServer_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUESTEXAMPLE._serialized_start=34
  _REQUESTEXAMPLE._serialized_end=82
  _PINGMSG._serialized_start=84
  _PINGMSG._serialized_end=106
  _STATUS._serialized_start=108
  _STATUS._serialized_end=143
  _AIMODELSERVER._serialized_start=146
  _AIMODELSERVER._serialized_end=293
# @@protoc_insertion_point(module_scope)
